FROM grafana/grafana:latest
MAINTAINER bdelbosc

COPY common/grafana/provisioning/datasources/* /etc/grafana/provisioning/datasources/
COPY common/grafana/provisioning/dashboards/* /etc/grafana/provisioning/dashboards/
