{
 "title": "BrewMon Template",
 "description": "BrewPi and iSpindel metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   { "name": "beer_name", "label": "Beer", "query": "show series" }
  ]
 },
 "panels": [
  { "title": "BrewPi LCD", "type": "ryantxu-ajax-panel", "description": "Current BrewPi LCD", "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Beer",
   "type": "singlestat",
   "description": "Current Wort temperature",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$beer_name$/",
     "select": [
      [
       { "params": [ "beer_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Beer Setting",
   "type": "singlestat",
   "description": "The target temperature for the Wort",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$beer_name$/",
     "select": [
      [
       { "params": [ "fridge_setting_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "The current gap between beer and beer setting",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$beer_name$/",
     "query": "SELECT abs(mean(\"beer_temp\") - mean(\"beer_setting_temp\")) FROM /^$beer_name$/ WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "beer_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fridge",
   "type": "singlestat",
   "description": "The current Fridge temperature",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$beer_name$/",
     "select": [
      [
       { "params": [ "fridge_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fridge Setting",
   "type": "singlestat",
   "description": "The target Fridge temperature driven by BrewPi",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$beer_name$/",
     "select": [
      [
       { "params": [ "fridge_setting_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "The current gap between fridge and fridge setting",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "/^$beer_name$/",
     "query": "SELECT abs(mean(\"fridge_temp\") - mean(\"fridge_setting_temp\")) FROM /^$beer_name$/ WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "beer_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gravity",
   "type": "singlestat",
   "description": "Current gravity in Plato",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurements",
     "select": [
      [
       { "params": [ "gravity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "iSpindel Bat.",
   "type": "singlestat",
   "description": "Battery",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurements",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "description": "Temperatures from BrewPi",
   "gridPos": { "h": 15, "w": 21, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^$beer_name$/",
     "query": "SELECT mean(\"state_cooling\") AS \"Cooling\", mean(\"state_heating\") AS \"Heating\" FROM /^$beer_name$/ WHERE $timeFilter  GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "beer_temp" ], "type": "field" },
       { "params": [ "Beer" ], "type": "alias" }
      ],
      [
       { "params": [ "fridge_temp" ], "type": "field" },
       { "params": [ "Fridge" ], "type": "alias" }
      ],
      [
       { "params": [ "state_cooling" ], "type": "field" },
       { "params": [ "Cooling" ], "type": "alias" }
      ],
      [
       { "params": [ "state_heating" ], "type": "field" },
       { "params": [ "Heating" ], "type": "alias" }
      ],
      [
       { "params": [ "room_temp" ], "type": "field" },
       { "params": [ "Room" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "measurements",
     "query": "SELECT mean(\"gravity\") AS \"Gravity\" FROM \"measurements\" WHERE $timeFilter  GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "gravity" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "/^$beer_name$/",
     "query": "SELECT mean(\"room_temp\") AS \"Room\", mean(\"fridge_setting_temp\") AS \"Fridge Setting\", mean(\"fridge_temp\") AS \"Fridge\", mean(\"beer_setting_temp\") AS \"Beer Setting\", mean(\"beer_temp\") AS \"Beer\" FROM /^$beer_name$/ WHERE $timeFilter  GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "beer_temp" ], "type": "field" },
       { "params": [ "Beer" ], "type": "alias" }
      ],
      [
       { "params": [ "fridge_temp" ], "type": "field" },
       { "params": [ "Fridge" ], "type": "alias" }
      ],
      [
       { "params": [ "state_cooling" ], "type": "field" },
       { "params": [ "Cooling" ], "type": "alias" }
      ],
      [
       { "params": [ "state_heating" ], "type": "field" },
       { "params": [ "Heating" ], "type": "alias" }
      ],
      [
       { "params": [ "room_temp" ], "type": "field" },
       { "params": [ "Room" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "iSpindel",
   "type": "graph",
   "description": "Gravity and temperature from iSpindel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "degree", "label": "Plato" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measurements",
     "select": [
      [
       { "params": [ "RSSI" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "RSSI" ], "type": "alias" }
      ],
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "battery" ], "type": "alias" }
      ],
      [
       { "params": [ "gravity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "gravity" ], "type": "alias" }
      ],
      [
       { "params": [ "tilt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tilt" ], "type": "alias" }
      ],
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "temperature" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}